/control/verbose 2
/run/verbose 2

/run/initialize


/vis/open OGL 600x600-0+0
/vis/viewer/set/viewpointThetaPhi 180. 0.
/vis/viewer/zoom 1.2
/vis/drawVolume

# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2


/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon blue
/vis/modeling/trajectories/drawByParticleID-0/set neutrino white

/vis/scene/add/hits

# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! Compton Experiment

/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)


#/vis/scene/add/axes 0 0 0 2 cm # Simple axes: x=red, y=green, z=blue.

# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)


#######################################
#           Visibility
#######################################
/vis/geometry/set/visibility logicWorld 0 false

#######################################
#           Colours
#######################################

#/vis/viewer/set/hiddenMarker false


/vis/viewer/set/autoRefresh true
/vis/scene/add/hits
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
/vis/ogl/set/displayListLimit 5000000
#/vis/viewer/flush

/NameOfFile/NameOfFile Prova
